version: "3"

services:
  todosDB:
    image: postgres:15.3
    container_name: todos-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
